language: node_js
node_js:
  - "node"
dist: xenial  
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://52.160.65.48:2376"
    - DOCKER_CERT_PATH="$TRAVIS_BUILD_DIR/azure"
    - DOCKER_MACHINE_NAME="dronuts2021-team-7"

script:
  - npm install
  - npm test
  - docker-compose build

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose up -d --remove-orphans
  on:
    branch: master
