version: '3'
services:

  your_app:
    container_name: your_app
    build: ./
    ports:
      - "80:3000"
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypwd123
